### ISSUE TITLE
Create documentation for Terms and Conditions of using business information

### ISSUE THREAD

**Issue by edmundchan8** [Cascadia-Connections/orca-stars#12]
There needs to be a document that businesses, when they sign up for OrcaStars, need to be able to view, like a terms and conditions document, that would confirm OrcaStars will have the businesses approvals to use their name, logo, etc on their website

**Comment by Bansenauer-Cascadia** [comment]
This is a Product Backlog item rather than a issue at this point. Put it on the list and set its priority

**Comment by edmundchan8** [comment]
thanks!
