### ISSUE TITLE
Create the Model and the Controller for Business application form

### ISSUE THREAD

**Issue by nateptay** [Cascadia-Connections/orca-stars#15]
Creating the Model and Controller to navigate through the business form for the application
DOD: The Controller can use the model to submit an application
User Story 3: Fill out a form to add an Orca Star Business

**Comment by nateptay** [comment]
> Create the Model and the Controller for Business application form #15
Creating the Model and Controller to navigate through the business form for the application
Done when: The Controller can use the model to submit an application
<https://github.com/Cascadia-Connections/orca-stars/issues/15>
<sub>[View in Slack](https://orca-stars.slack.com/archives/C011G71123H/p1586994950006500)</sub>

**Comment by edmundchan8** [comment]
Archived - Added to product backlog
