### ISSUE TITLE
Submit Business Information

### ISSUE THREAD

**Issue by edmundchan8** [Cascadia-Connections/orca-stars#25]
DOD: The business information form can be submitted
Description: Use the controller to navigate from a completed form to a confirmation page

**Comment by nateptay** [comment]
User Story 5: As a user/administrator of the web application, I want to be able to take a business applicaiton form and enter in their information into the web application, and when I process the data it gets updated and added to the database.

Use Case 4: Precondition: A business has been approved for the OrcaStar App
Description: An administrator enters the business' name into a form, and submits it to the OrcaStar database
Post Condition: The business' information is stored in the OrcaStars database.
Exception: If necessary information is incomplete, the administrator will be prompted to enter the missing information.
