### ISSUE TITLE
Create entity model and database for application web form

### ISSUE THREAD

**Issue by edmundchan8** [Cascadia-Connections/orca-stars#5]
Creating the database to store business information from the web form

**Comment by Bansenauer-Cascadia** [comment]
Please add a clear Definition of Done (DoD) that describes, how someone would know that this is complete.

**Comment by madelynmlocke** [comment]
**Issue/Task Description:**
Create entity model and database for application web form

**DOD:**
 User can post an approved business application to be stored into the database. 

**User Story and Use Case:**
Not Applicable.
